defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.eval.eval_reflow_mikasa_mem_agent.EvalReFlowMikasaMemAgent

name: ${env_name}_eval_reflow_mem_ta${horizon_steps}_td${denoising_steps}
logdir: 
  ${oc.env:REINFLOW_LOG_DIR}/mikasa/eval/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
#base_policy_path: ${oc.env:REINFLOW_LOG_DIR}/mikasa/finetune/RememberShapeAndColor3x2-v0_ft_reflow_mem_learned_matrix_Temp0.01_0.02_tdf5/2025-11-01_03-55-07_42/checkpoint/best.pt
#base_policy_path: ${oc.env:REINFLOW_LOG_DIR}/mikasa/finetune/RememberShapeAndColor3x2-v0_ft_reflow_mem_learned_matrix_ta4_td5_tdf5/2025-11-01_01-59-26_42/checkpoint/best.pt
#base_policy_path: ${oc.env:REINFLOW_LOG_DIR}/mikasa/finetune/RememberShapeAndColor3x2-v0_ft_reflow_mem_learned_matrix_ta4_td5_tdf5/2025-10-31_11-54-20_42/checkpoint/best.pt
#base_policy_path: ${oc.env:REINFLOW_LOG_DIR}/mikasa/finetune/RememberShapeAndColor3x2-v0_ft_reflow_mem_learned_vector_ta4_td5_tdf5/Best/best.pt
#base_policy_path: ${oc.env:REINFLOW_LOG_DIR}/mikasa/pretrain/RememberShapeAndColor3x2-v0/RememberShapeAndColor3x2-v0_pre_reflow_mlp_img_ta4_td100/2025-11-02_05-36-17_42/checkpoint/state_1500.pt
#base_policy_path: ${oc.env:REINFLOW_LOG_DIR}/mikasa/pretrain/RememberShapeAndColor3x2-v0/RememberShapeAndColor3x2-v0_pre_reflow_mlp_img_ta4_td100/2025-11-02_03-47-48_42/checkpoint/state_500.pt
base_policy_path: ${oc.env:REINFLOW_LOG_DIR}/mikasa/finetune/RememberShapeAndColor3x2-v0_ft_reflow_mem_learned_matrix_from_pretrain_tanh_Temp0.04_0.08_tdf5/2025-11-02_10-55-24_33/checkpoint/state_90.pt
load_ema: False
seed: 42
device: cuda:0
env_name: RememberShapeAndColor3x2-v0
obs_dim: 25
action_dim: 8
denoising_steps: 100
cond_steps: 1
img_cond_steps: 1
horizon_steps: 4
act_steps: 4
denoising_step_list: [5]

n_steps: 60  # each episode takes max_episode_steps / act_steps steps
render_num: 1
batch_size: 128

record_video: true
frame_width: 640
frame_height: 480
record_env_index: 0

record_memory_heatmap: true
memory_record_env_index: 0
memory_heatmap_max_steps: 80

env:
  env_type: mikasa  # 关键：指定mikasa环境类型
  n_envs: 1
  name: ${env_name}
  save_video: true
  use_custom_video: true
  video_dir: ${logdir}/videos # where to save the videos
  best_reward_threshold_for_success: 1
  max_episode_steps: 60
  use_image_obs: true
  wrappers:
    mikasa:  # 使用mikasa wrapper替代robomimic_image
      rgb: true
      depth: false
      state: false
      oracle: false
      joints: true
      target_camera: "base_camera"
      # normalization_path: null  # 没有normalization文件，设为null或完全省略
      clamp_obs: false
    render_step_info:
      {} # empty dict means no kwargs
    render_reward_info:
      {}
    #render_target_info:
    #  _target_: mikasa_robo_suite.utils.wrappers.RenderTargetInfoWrapper
    remember_shape_and_color_info:
      {}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true
  render: true

shape_meta:
  obs:
    rgb:
      shape: [3, 128, 128]  # image shape
    state:
      shape: [25]
  action:
    shape: [8]

model:
  _target_: model.flow.reflow.ReFlow
  network:
    _target_: model.flow.mlp_memorybank.VisionFlowMLPMembank
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape: ${shape_meta.obs.rgb.shape}
      num_channel: ${eval:'${shape_meta.obs.rgb.shape[0]} * ${img_cond_steps}'} # each image patch is history concatenated
      img_h: ${shape_meta.obs.rgb.shape[1]}
      img_w: ${shape_meta.obs.rgb.shape[2]}
      cfg:
        patch_size: 8
        depth: 1
        embed_dim: 128
        num_heads: 4
        embed_style: embed2
        embed_norm: 0
    img_cond_steps: ${img_cond_steps}
    augment: false
    spatial_emb: 128
    time_dim: 32
    mlp_dims: [512, 512, 512]
    residual_style: true
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1
  obs_dim: ${obs_dim}
  max_denoising_steps: ${denoising_steps}
  seed: ${seed}
  sample_t_type: uniform # beta, logitnormal

memory:
  _target_: model.common.learned_memory.PatchWorkingMemory
  embed_dim: 128
  num_slots: null        # 留空就会自动用 backbone.num_patch，也可以直接写死 196
  read_temperature: 0.04
  write_temperature: 0.08
  use_topk: false
  topk: 16
  residual_scale: 1.0
  normalize: true
#memory:
#  _target_: model.common.learned_memory.LearnedWorkingMemoryLite
#  embed_dim: 128
#  temperature: 0.07
#  write_temperature: 0.14
#  alpha_min: 0.02
#  alpha_max: 0.25
#  normalize: true
